---
title: "Programación y manejo de datos (Respuestas al examen final)"


author: 
- name: Carles Soler Sanchis (carsosa3@alumni.uv.es)
  affiliation: Universitat de València
  affiliation-url: https://www.uv.es

date: 07-01-2025

format:
  html:
    theme: journal  
    highlight-style: a11y  
    page-layout: full  
    fontcolor: black
    backgroundcolor: "#98FB98"
title-block-style: default #- {default, plain, none}
title-block-banner-color: green

css: assets/my_styles.css         
---

## Descargar archivo qmd
Se puede descargar el .qmd en el siguiente link:
<a href="index.qmd" download>Descargar Archivo</a>

---

# Pregunta 1

```{r}
#Paquetes que vamos a usar en el examen:
library(tidyverse)
library(ggplot2)
library(dplyr)
library(gapminder)
library(tidyr)
library(knitr)
library(vembedr)
library(readr)
library(readxl)
library(rio)


df <- gapminder::gapminder
```

### 1.1

```{r}
aa <- df %>% 
  filter(continent == "Africa", year == 1992 ) %>%
  arrange(desc(gdpPercap)) %>%
  slice(1:4)

```

### 1.2

```{r}
bb <- df %>%
  filter(continent == "Europe", year == 2002, gdpPercap < 8000)
  print(bb)
```

### 1.3

```{r}
rm(list = ls())

```

### 1.4

```{r}

```

### 1.5

```{r}

```

# Pregunta 2

### 2.1

```{r}
library(rio)
datos <- rio::import("datos/56934.xlsx")
```

### 2.2

```{r}

```

### 2.3

```{r}

```

### 2.4

```{r}

```

### 2.5

```{r}

```

# Pregunta 3

### 3.1

```{r}

```

### 3.2

```{r}

```

### 3.3

```{r}

```

### 3.4

```{r}

```

### 3.5

```{r}

```

# Pregunta 4

### 4.1

```{r}

```

### 4.2

```{r}

```

### 4.3

```{r}

```

### 4.4

```{r}

```

### 4.5

```{r}

```

# Pregunta 5

### 5.1

```{r}
library(vembedr)
embed_url("https://www.youtube.com/watch?v=kFSrwav583o")
```

### 5.2

```{r}

```

### 5.3

```{r}

```

### 5.4

```{r}

```

### 5.5

```{r}

```






---
